<!--<pre>
<?//print_r($this->calendar['info'])?>
</pre>-->
<div class="row-fluid">
		<!-- left SIDE-->   
	<div class="span12"> 
	<h3><?if(!empty($this->calendar['info']['ClinicName'.$this->lang])):?>
            <?=$this->calendar['info']['ClinicName'.$this->lang]?><?endif?></h3>
	<div class="span5">
	<div class="well">	
		<address>
			<strong><?if(!empty($this->calendar['info']['ClinicName'.$this->lang])):?>
            <?=$this->calendar['info']['ClinicName'.$this->lang]?><?endif?></strong><br>
			<?if(!empty($this->calendar['info']['ClinicStreet'.$this->lang])):?>
                                                <?=$this->calendar['info']['ClinicStreet'.$this->lang]?><?endif?><br>
			San Francisco, CA 94107<br>
			<abbr title="Phone">P:</abbr> <?if(!empty($this->calendar['info']['ClinicTel'])):?>
                                                <?=$this->calendar['info']['ClinicTel']?><?endif?>
			<a href="mailto:#">first.last@gmail.com</a>
		</address>
	</div>
 </div>
 </div>
 <div class="span12"> 

     <h4><?= $this->translate('Расписание работы врача:'); ?><strong>Акушер</strong></h4> 
	<table class="table table-hover">
        <thead>
            <tr><th></th>
                <th><span></span><span ><?= $this->translate('Monday'); ?></span></th>
                <th><span ><?= $this->translate('Tuesday'); ?></span> </th>
                <th><span ><?= $this->translate('Wednesday'); ?></span> </th>
                <th><span ><?= $this->translate('Thursday'); ?></span> </th>
                <th><span ><?= $this->translate('Friday'); ?></span> </th>
                <th><span ><?= $this->translate('Saturday'); ?></span></th>
                <th><span ><?= $this->translate('Sunday'); ?></span> </th>
        </tr></thead>
        <tbody id="calendarBody">
                <?if(!empty($this->calendar['schedule'])):?>
                    <?foreach($this->calendar['schedule'] as $row):?>
                    <tr> 
                        <td><?=$row['DocName'+$this->lang]?></td>          
                        <td><?=$row['Monday']?></td>          
                        <td><?=$row['Tuesday']?></td>          
                        <td><?=$row['Wednesday']?></td>          
                        <td><?=$row['Thursday']?></td>          
                        <td><?=$row['Friday']?></td>          
                        <td><?=$row['Saturday']?></td>          
                        <td><?=$row['Sunday']?></td>          
                    </tr>
                    <?endforeach;?>
                <?endif;?>
        </tbody>
    </table>
	
</div>

                