<link rel="stylesheet" type="text/css" href="/css/calendar.css" media="screen" />
<script src="/js/calendar_page.js"></script>
<div class = "top_inputs">
        <?=$this->translate('Region')?>: 
            <select id="region" class = "search_right" disabled ="disabled">
                 <option value=""></option>
                 <?if(!empty($this->regions)):?>
                    <?foreach($this->regions as $regionId => $regionName):?>
                        <option <?if($regionId == 1):?>selected="selected"<?endif;?>value="<?=$regionId?>"><?=$regionName?></option>
                    <?endforeach;?>
                <?endif;?>
            </select>
        <?=$this->translate('Nasel punkt')?>:
            <select id="city" class = "search_right" disabled ="disabled">
                <option value=""></option>
                 <?if(!empty($this->city)):?>
                    <?foreach($this->city as $cityId => $cityName):?>
                        <option <?if($cityId == 25):?>selected="selected"<?endif;?>value="<?=$cityId?>"><?=$cityName?></option>
                    <?endforeach;?>
                <?endif;?>
            </select>
        <?=$this->translate('Type of state')?>:
        <select id="clinicType"class = "search_right">
            <option value=""><?=$this->translate('All')?></option>
            <?if(!empty($this->clinicType)):?>
            <?foreach($this->clinicType as $clinicType):?>
                <option value="<?=$clinicType['idtbl_clinic_type']?>"><?=$clinicType[$this->lang.'_name']?></option>
            <?endforeach;?>
            <?endif;?>
        </select>
    </div>    
<div class = "left_select">
    <input id="searchinput" type="text" placeholder="<?= $this->translate('Пошук: кардіолог або серце') ?>" class = "search">
    <select id="doctortype" size="16"  class = "doc_type_select">
        <?if(!empty($this->doctorType)):?>
            <?foreach($this->doctorType as $doctorType):?>
                <option value="<?=$doctorType['TypeDocID']?>"><?=$doctorType[$this->lang.'_name']?></option>
            <?endforeach;?>
         <?endif;?>
    </select>
</div>
<div class = "center_select">
    <div id ="hoshital_type" class = "hoshital_type_select" style="overflow-x: hidden;">
        <div class="rr_welcome_text"><p class="rr_welcome"><?= $this->translate('Вітаємо на сайті медичної довідки') ?></p>
            <p class="rr_instruction"><?= $this->translate('Щоб дізнатися розклад роботи лікаря Вам необхідно:') ?></p>
            <ul>
                <li><?= $this->translate('Ввести в пошук спеціальність лікаря, або назву орану, на якому спеціалізується лікар;') ?></li>
                <li><?= $this->translate('Обрати спеціальність лікаря;') ?></li>
                <li><?= $this->translate('Обрати лікарню, що Вас цікавить;') ?></li>
                <li><?= $this->translate('Розклад лікарів обраної Вами спеціальності та лікарні буде відображено внизу сторінки.') ?></li>
            </ul>
                
        </div>
      </div>
<!--    <select id ="hoshital_type" size="18" multiple="multiple" class = "hoshital_type_select">
       
    </select>-->
</div>
<div class = "clear"></div>
<div id="calendar" <?if(empty($this->calendar)):?>style="display: none<?endif;?>">
    <div class = "calendarHead">
<!--        <div id ="l" style="display: none"><?//=$this->L?></div>
        <div class = "listweek" style="float: left;"><a onclick ="getPreviousWeek()">Previous week</a></div>
        <div class = "listmonth" >
            <span id='month'  attr="<?//=$this->monthNumber?>"><?//=$this->month?></span>
            <span id='year'><?//=$this->year?></span>
        </div>
        <div class = "listweek" style="float: left;"><a onclick ="getNextWeek()">Next week</a></div>
        <div style="clear:both"></div>-->
    </div>
    <table >
        <thead>
            <th></th>
            <th><span id='fday'><?//=$this->week_start?></span><span class = "week_day"><?=$this->translate('Monday')?></span></th>
            <?$now =  strtotime($this->week_start.' '.$this->month.' '.$this->year)?>
            <th><?//=date('j', strtotime("+1 day", $now))?><span class = "week_day"><?=$this->translate('Thursday')?></span> </th>
            <th><?//=date('j', strtotime("+2 day", $now))?><span class = "week_day"><?=$this->translate('Wednesday')?></span> </th>
            <th><?//=date('j', strtotime("+3 day", $now))?><span class = "week_day"><?=$this->translate('Tuesday')?></span> </th>
            <th><?//=date('j', strtotime("+4 day", $now))?><span class = "week_day"><?=$this->translate('Friday')?></span> </th>
            <th><?//=date('j', strtotime("+5 day", $now))?><span class = "week_day"><?=$this->translate('Saturday')?></span></th>
            <th><?//=date('j', strtotime("+6 day", $now))?><span class = "week_day"><?=$this->translate('Sunday')?></span> </th>
        </thead>
        <tbody id="calendarBody">
            <?if(!empty($this->calendar["schedule"])):?>
            <?foreach($this->calendar["schedule"] as $oneRow):?>
            <tr class = "htmlspechchars">
                <td><?=$oneRow['DocName'.strtoupper($this->lang)];?></td> 
                <td>
                    <?if($oneRow['Monday_type'] == 0):?>
                        <?=$oneRow['Monday']?>
                    <?elseif($oneRow['Monday_type']== 1):?>
                        <?=$oneRow['Monday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Monday_url'];?>">
                    <?endif;?>
                </td> 
                <td>
                    <?if($oneRow['Tuesday_type'] == 0):?>
                        <?=$oneRow['Tuesday']?>
                    <?elseif($oneRow['Tuesday_type']== 1):?>
                        <?=$oneRow['Tuesday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Tuesday_url'];?>">
                    <?endif;?>
                </td> 
                <td>
                    <?if($oneRow['Wednesday_type'] == 0):?>
                        <?=$oneRow['Wednesday']?>
                    <?elseif($oneRow['Wednesday_type']== 1):?>
                        <?=$oneRow['Wednesday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Wednesday_url'];?>">
                    <?endif;?>
                </td> 
                <td>
                    <?if($oneRow['Thursday_type'] == 0):?>
                        <?=$oneRow['Thursday']?>
                    <?elseif($oneRow['Thursday_type']== 1):?>
                        <?=$oneRow['Thursday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Thursday_url'];?>">
                    <?endif;?>
                </td> 
                <td>
                    <?if($oneRow['Friday_type'] == 0):?>
                        <?=$oneRow['Friday']?>
                    <?elseif($oneRow['Friday_type']== 1):?>
                        <?=$oneRow['Friday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Friday_url'];?>">
                    <?endif;?>
                </td> 
                <td>
                    <?if($oneRow['Saturday_type'] == 0):?>
                        <?=$oneRow['Saturday']?>
                    <?elseif($oneRow['Saturday_type']== 1):?>
                        <?=$oneRow['Saturday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Saturday_url'];?>">
                    <?endif;?>
                </td> 
                <td>
                    <?if($oneRow['Sunday_type'] == 0):?>
                        <?=$oneRow['Sunday']?>
                    <?elseif($oneRow['Sunday_type']== 1):?>
                        <?=$oneRow['Sunday_info_'.$this->lang]?>
                    <?else:?>
                        <img class = "small_img" src="<?=$oneRow['Sunday_url'];?>">
                    <?endif;?>
                </td> 
            </tr>
            <?endforeach;?>
            <?endif;?>
        </tbody>
    </table>
    <div id ="clinicinfo" class = "clinic_info"></div>
</div>

<script id="cityTemplate" type="text/x-jquery-tmpl">
      <option value="${idtbl_city}">${<?=$this->lang?>.'_name}</option>
</script>
<script id="doctortypeTemplate" type="text/x-jquery-tmpl">
      <option value="${TypeDocID}">${<?=$this->lang?>_name}</option>
</script>
<script id="hoshital_typeTemplate" type="text/x-jquery-tmpl">
    <div class = "hospital_select" paramID="${ClinicID}">
        <span class = "clinicName">
            ${ClinicName<?=strtoupper($this->lang)?>}
        </span>
        <br>
        <span class = "clinicTypeText">${ClinicType<?=strtoupper($this->lang)?>}</span> &nbsp;&nbsp;&nbsp;
        <span class = "textDescribe">${ClinicStreet<?=strtoupper($this->lang)?>}&nbsp;&nbsp;&nbsp;${ClinicTel}</span>
    </div>
</script>
<script id="calendarTemplate" type="text/x-jquery-tmpl">
    <tr class = "htmlspechchars">
        <td>${DocName<?=strtoupper($this->lang)?>}</td> 
        <td>{{if Monday_type == 0}}${Monday}{{else}}{{if Monday_type == 1}}${Monday_info_<?=$this->lang?>}{{else}}<img class = "small_img" src="${Monday_url}">{{/if}}{{/if}}</td> 
        <td>{{if Tuesday_type == 0}}${Tuesday}{{else}}{{if Tuesday_type == 1}}${Tuesday_info_<?=$this->lang?>}{{else}}<img class = "small_img" src="${Tuesday_url}">{{/if}}{{/if}}</td> 
        <td>{{if Wednesday_type == 0}}${Wednesday}{{else}}{{if Wednesday_type == 1}}${Wednesday_info_<?=$this->lang?>}{{else}}<img class = "small_img" src="${Wednesday_url}">{{/if}}{{/if}}</td> 
        <td>{{if Thursday_type == 0}}${Thursday}{{else}}{{if Thursday_type == 1}}${Thursday_info_<?=$this->lang?>}{{else}}<img class = "small_img" src="${Thursday_url}">{{/if}}{{/if}}</td> 
        <td>{{if Friday_type == 0}}${Friday}{{else}}{{if Friday_type == 1}}${Friday_info_<?=$this->lang?>}{{else}}<img class = "small_img" src="${Friday_url}">{{/if}}{{/if}}</td> 
        <td>{{if Saturday_type == 0}}${Saturday}{{else}}{{if Saturday_type == 1}}${Saturday_info_<?=$this->lang?>}{{else}}<img  class = "small_img" src="${Saturday_url}">{{/if}}{{/if}}</td> 
        <td>{{if Sunday_type == 0}}${Sunday}{{else}}{{if Sunday_type == 1}}${Sunday_info_<?=$this->lang?>}{{else}}<img class = "small_img" src="${Sunday_url}">{{/if}}{{/if}}</td> 
    </tr>
</script>
<script>
    function updateDoctorType(cityID, clinicTypeID, searchText){
    $.post('/default/ajax/getdoctorstypeforcity', {
        cityID:cityID, 
        clinicType:clinicTypeID , 
        searchText: searchText,
        uds_lang: '<?=Zend_Registry::get('uds_lang')?>'
    }, function(resp){
        select_option = $("#doctortypeTemplate").tmpl(JSON.parse(resp.data));
        $("#doctortype").html(select_option);
        clinClinCalendar();
        clinClinic();
    }, 'json');
}
function updateCalendar(clinicID, doctorTypeID){
    $.post('/default/ajax/getcalendar', {
        clinicID:clinicID,
        doctorTypeID:doctorTypeID
    }, function(resp){
        history.pushState('','','?clinicID='+clinicID+'&doctorTypeID='+doctorTypeID);
        if(resp.data != '[]'){
            select_option = $("#calendarTemplate").tmpl(JSON.parse(resp.data));
            $("#calendarBody").html(select_option);
            $("#calendarBody").html(html_entity_decode($("#calendarBody").html()));
            $('#calendar').show();}
        else{
             $('#calendar').hide();
        }
        $('#clinicinfo').html(JSON.parse(resp.info)['<?=Zend_Registry::get('uds_lang')?>_about'])   ;
        if($('#clinicinfo').text()!='')
            $('#clinicinfo').show(); 
        else $('#clinicinfo').hide();
    }, 'json');
}
    </script>