<? $lang = explode('/', $_SERVER['REQUEST_URI']);
$lang = $lang[1]; ?> 

<!--<link rel="stylesheet" type="text/css" href="/css/med_login.css"/>-->

    <form id="LoginForm" action ="<?= $this->url(array(), 'login') ?>" class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="input-block-level" placeholder="<?= $this->translate('Login') ?>" id="username" name="username">
        <input type="password" class="input-block-level" placeholder="<?= $this->translate('Password') ?>" id="password" name="password">
        <div style ="color: #CA3D26; margin-bottom: 10px;">
                <?= $this->errMessage ?>
        </div>
        <a href="<?= $this->url(array('lang' => $lang), 'registration') ?>" class="btn " type="submit"><?= $this->translate('Signup') ?></a>
        <a href="<?= $this->url(array('lang' => $lang), 'restorepass') ?>" class="btn " type="submit"><?= $this->translate('Restore password') ?></a>
        <a ref="javascript:void(0)" id ="loginLink" class="btn btn-success" type="submit"><?= $this->translate('Enter') ?></a>
    </form>

<div id="result"></div>
    
<script>
    function registPopup() {
        $.ajax({
            url: "/default/registration/form",
            metod: "post",
            success: function(data) {
                $("#result").html(data);
            }
        });
    }
    $(document).ready(function() {
        $('#loginLink').click(function() {
            $('#LoginForm').submit();
        });
        $('form').keydown(function(event) {
            if (event.keyCode == 13)
                $('#LoginForm').submit();
        })
    })
</script>