<title>Welcome | Obmen</title>
<link rel="shortcut icon" href="/favicon.ico" type="image/png">
<meta name="title" content="<?=$this->shareTitle;?>" />
<meta name="description" content="<?=$this->shareMessage;?>" />
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<?php echo $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
                      ->appendHttpEquiv('Content-Language', 'en-US')
                      ->appendHttpEquiv('viewport', 'width=device-width, initial-scale=1.0');
      echo $this->headScript()->prependFile('/js/jquery-1.6.4.min.js')
//                              ->appendFile('/js/datepicker/jquery.ui.core.js')
//                              ->appendFile('/js/datepicker/jquery.ui.widget.js')
//                              ->appendFile('/js/datepicker/jquery.ui.mouse.js')
//                              ->appendFile('/js/datepicker/jquery.ui.datepicker.js')
//                              ->appendFile('/js/datepicker/jquery.ui.slider.js')
//                              ->appendFile('/js/slides.js')
//                              ->appendFile('/js/dealSlider.js')
//                              ->appendFile('/js/jquery.hoverIntent.minified.js')
//                              ->appendFile('/js/colorbox/jquery.colorbox.js')
//                              ->appendFile('/js/jquery-spin.js')
//                              ->appendFile('/js/jquery-cookie.js')
                              ->appendFile('/js/jquery.dropDown.pack.js')
                              ->appendFile('/js/jquery.groupinputs.min.js')
                              ->appendFile('/js/jquery.caret.1.2.min.js')
                              ->appendFile('/js/jquery.tmpl.min.js')
                              ->appendFile('/js/jquery.form.js');
//      echo $this->headLink()->appendStylesheet('/css/base.css');
//                            ->appendStylesheet('/css/colorbox/colorbox.css')
//                            ->appendStylesheet('/css/slide.css')
//                            ->appendStylesheet('/css/datepicker/jquery-ui-1.8.16.custom.css');
//       echo $this->headLink()->appendStylesheet('/css/med.css')
         echo $this->headLink()->appendStylesheet('/css/firstform.css')
                             ->appendStylesheet('/css/layout.css')
                             ->appendStylesheet('/css/bootstrap.min.css')
                             ->appendStylesheet('/css/bootstrap-responsive.css')
                             ->appendStylesheet('/css/font-awesome.min.css')
                             ->appendStylesheet('/css/jquery.mCustomScrollbar.css')
                             ->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:700italic,400,300,700&subset=latin,cyrillic-ext')
//                              ->appendStylesheet('/css/site.css');

?>
<link rel="shortcut icon" href="/assets/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
<!--<script src="/js/jquery.js" type="text/javascript"></script>-->
<script src="/js/bootstrap-transition.js" type="text/javascript"></script> 
<script src="/js/bootstrap-alert.js" type="text/javascript"></script> 
<script src="/js/bootstrap-modal.js" type="text/javascript"></script> 
<script src="/js/bootstrap-dropdown.js" type="text/javascript"></script> 
<script src="/js/bootstrap-scrollspy.js" type="text/javascript"></script> 
<script src="/js/bootstrap-tab.js" type="text/javascript"></script> 
<script src="/js/bootstrap-tooltip.js" type="text/javascript"></script> 
<script src="/js/bootstrap-popover.js" type="text/javascript"></script> 
<script src="/js/bootstrap-button.js" type="text/javascript"></script> 
<script src="/js/bootstrap-collapse.js" type="text/javascript"></script> 
<script src="/js/bootstrap-carousel.js" type="text/javascript"></script> 
<script src="/js/bootstrap-typeahead.js" type="text/javascript"></script> 
<script src="/js/bootstrap-affix.js" type="text/javascript"></script>
<script src="/js/jquery.localscroll-1.2.7-min.js" type="text/javascript"></script>
<script src="/js/jquery.scrollTo-1.4.2-min.js" type="text/javascript"></script>
<script src="/js/jquery.mousewheel.js" type="text/javascript"></script>
<script src="/js/jquery.mCustomScrollbar.js" type="text/javascript"></script>
<!-- USE PREFIX fa- e.g (<i class="fa-icon-home"></i> -->

<!--[if lt IE 7]>
	<link href="/css/font-awesome-ie7.min.css" rel="stylesheet">
	<![endif]-->
    <!-- Fav and touch icons -->


<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
