<!DOCTYPE html>
<html land="ru">

    <head>
        <?php echo $this->partial("head.phtml"); ?>
    </head>
    <body>
                <?php echo $this->render("header.phtml"); ?>
        <div class="container">
    <!-- Example row of columns -->
    <div class="row-fluid">
                        <?php echo $this->layout()->content; ?>
        </div></div>
            <?php  echo $this->partial("footer.phtml"); ?>
    </body>

</html>
