<?$lang = explode('/', $_SERVER['REQUEST_URI']); $lang= $lang[1];?>
<div class="sucRegistr">
    <div>
        <div id="answer" class="otst">
            <?= $this->translate('We will sent message with new password to you email.') ?>
            <br><?= $this->translate('Enter your email') ?>
            
        </div>
        <div id="blockChangePass" class="otst">
            <form id="changePass" metod="post" action="/default/registration/updatepass">
                <input id="usermail" type="text" name="email"/>
                <button id="subm" type="submit"><?= $this->translate('Send') ?></button>
            </form>
        </div>
    </div>
</div>
<div class="sucRegistr" style ="display: none" id="positiv">
    <div>
        <?= $this->translate('The message with new password was send to you email.') ?><br> 
        <?=$this->translate('For go to base page')?> <a href="<?= $this->url(array('lang'=>$lang), 'base')?>"> <?=$this->translate('press to link')?></a>.
    </div>
</div>
<div class="sucRegistr" style ="display: none" id="negative3">
    <div>
        <?= $this->translate('There are no account registarited to this email in this site.') ?>
       <br>
        <?= $this->translate('Enter your email') ?>
    </div>
</div>
<div class="sucRegistr" style ="display: none" id="negative2">
    <div>
        <?= $this->translate('Enter your email') ?>
    </div>
</div>

<script type="text/javascript">
        $(document).ready(function(){
            $("#changePass").ajaxForm(function(result){
                if(result.type == 1){
                    $('#blockChangePass').hide();
                    $('#answer').html($('#positiv').html());
                }else if(result.type == 2){
                    $('#blockChangePass').show();
                    $('#answer').html($('#negative2').html());
                }else if(result.type == 3){
                    $('#blockChangePass').show();
                    $('#answer').html($('#negative3').html());
                }                
            });
        });
</script>

